### ISSUE TITLE
小萌新首先谢谢大佬的整理，小萌新发现大佬的笔误.....  :)

### ISSUE THREAD

**Issue by Zealousxin** [TangBean/understanding-the-jvm#1]
![image](https://user-images.githubusercontent.com/33589246/54084716-2accb380-436f-11e9-8dff-11a4df10f6ed.png)
![image](https://user-images.githubusercontent.com/33589246/54084739-6cf5f500-436f-11e9-811b-5b3ce42f50fe.png)

**Comment by TangBean** [comment]
是应该写成：“这东西又有好多种” 吗？

**Comment by TangBean** [comment]
这回读起来应该通顺了 =￣ω￣=

**Comment by TangBean** [comment]
这回读起来应该通顺了 =￣ω￣=

**Comment by TangBean** [comment]
这回读起来应该通顺了 =￣ω￣=
